Import('xn_env')
Import('TracesDisabled')

srcs = xn_env.AutoSplit('''filesystem.c trace_dumper.c writer.c buffers.c init.c open_close.c metadata.c''')
libs = ["tracereader", "rt", "trace_util_traced"]
prog = xn_env.XnProgram(target = "trace_dumper", source = srcs, LIBS = libs)
xn_env.Alias('xn', prog)


