Import('xn_env')
Import('TracesDisabled')

import subprocess
def get_llvm_build_flags(queries):
	p = subprocess.Popen(["llvm-config"] + queries.strip().split(), stdout=subprocess.PIPE)
	if p.wait() != 0:
		raise RuntimeError("Failed to query llvm-config for the flags: " + queries)
	return p.communicate()[0]

with TracesDisabled(xn_env) as untraced_env:
    srcs = untraced_env.Glob("*.cpp")
    ldflags = Split(get_llvm_build_flags("--libs --ldflags"))
    
    lib = untraced_env.SharedLibrary(target = 'trace_instrumentor_untraced', source = srcs, LDFLAGS=ldflags)
    untraced_env['CCFLAGS'] = Split(get_llvm_build_flags("--cxxflags")) + Split('-Wall -g')

    untraced_env.Alias('xn', lib)
    untraced_env.Alias('trace_instrumentor', lib)
